spring.application.name=marvinai
server.port=8181

spring.ai.mcp.server.name=marvinai-mcp-server-webflux
spring.ai.mcp.server.version=0.0.1

#logging.file.name=marvinai-mcp-server-webflux.log
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#datasource
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.microsoft.sqlserver.jdbc.SQLServerDriver}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://172.26.40.71:1433;databaseName=IPERUDB;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:iswadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Password2$}

## CORS CONFIG
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:*}
cors.allowed-methods=${CORS_ALLOWED_METHODS:POST,GET,PUT,OPTIONS,DELETE,PATCH}
cors.max-age=${CORS_MAX_AGE:3600}
cors.allowed-headers=${CORS_ALLOWED_HEADERS:*}
cors.exposed-headers=${CORS_EXPOSED_HEADERS:*}

#MSSQL HYBERNATE
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_HIBERNATE_DIALECT:org.hibernate.dialect.SQLServerDialect}
#spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
#spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:false}

spring.main.web-application-type=reactive

#LOGGING
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
management.endpoints.web.exposure.include=mappings
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.ai=TRACE
logging.level.io.modelcontextprotocol=TRACE
